local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/jensonhirst/Orion/main/source')))()
local Window = OrionLib:MakeWindow({Name = "✏️ chat 🐾", HidePremium = false, SaveConfig = true, ConfigFolder = "OrionTest", IntroText = "chat Script"})

--[[
Name = <string> - The name of the UI.
HidePremium = <bool> - Whether or not the user details shows Premium status or not.
SaveConfig = <bool> - Toggles the config saving in the UI.
ConfigFolder = <string> - The name of the folder where the configs are saved.
IntroEnabled = <bool> - Whether or not to show the intro animation.
IntroText = <string> - Text to show in the intro animation.
IntroIcon = <string> - URL to the image you want to use in the intro animation.
Icon = <string> - URL to the image you want displayed on the window.
CloseCallback = <function> - Function to execute when the window is closed.
]]
local Tab = Window:MakeTab({
	Name = "Chat",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})
Tab:AddLabel("The Chat tab. You can say something with the chat!")
Tab:AddParagraph("chat","oh hell nah, Chat tab is a tab where u can say anything without saying something in the chat lol idk why i put here soo long text but ok psx new cool doodle world update psx! pet simulator x is cool! LOL OLOL OL OL OLO OL LO OLOL OL L LO so i will be making updates soon ok long text sorry! ")
--[[
Name = <string> - The name of the tab.
Icon = <string> - The icon of the tab.
PremiumOnly = <bool> - Makes the tab accessible to Sirus Premium users only.
]]
---- Script generated by SimpleSpy - credits to exx#9394
Tab:AddTextbox({
	Name = "Say",
	Default = "Input Here",
	TextDisappear = true,
	Callback = function(Value)
		local args = {
            [1] = Value,
            [2] = "All"
        }
        
        game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
        
	end	  
})

--[[
Name = <string> - The name of the textbox.
Default = <string> - The default value of the textbox.
TextDisappear = <bool> - Makes the text disappear in the textbox after losing focus.
Callback = <function> - The function of the textbox.
]]
